In [2]:
import numpy as np

#### вариант 1

In [24]:
N = 13
dir_arr = np.arange(0, N)
rev_arr = dir_arr[::-1]
rev_arr

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### вариант 2

In [31]:
N1 = 15
dir_arr = np.arange(N1-1, -1, -1)
dir_arr

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2

In [38]:
N2 = 14
M1 = np.diag(np.arange(N2, -1, -1))
M1

array([[14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [95]:
print('Cумма элеметов на диагонали:', sum(M1.diagonal()))

Cумма элеметов на диагонали: 105


### Задание 3

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [46]:
A = np.array([[4, 2, 1],[1, 3, 0], [0, 5, 4]])
B = np.array([4, 12, -3])

In [47]:
X = np.linalg.solve(A, B)

In [48]:
X

array([ 0.46666667,  3.84444444, -5.55555556])

###### проверка

In [49]:
np.allclose(A.dot(X), B)

True

### Задание 4

In [90]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [91]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [92]:
def find_max_cos(users_stats, next_user_stats):
    list_cos = []
    for user_stats in users_stats:
        user_lenght = np.linalg.norm(user_stats)
        next_user_lenght = np.linalg.norm(next_user_stats)
        cos = np.dot(user_stats, next_user_stats) / (user_lenght * next_user_lenght)
        list_cos.append(cos)
    max(list_cos)
    print('ID пользователя самого похожего пользователя:', list_cos.index(max(list_cos))+1)

In [93]:
find_max_cos(users_stats, next_user_stats)

ID пользователя самого похожего пользователя: 8
