# Задание
● Создайте случайную матрицу А1 размерностью 5 на 5  
● Транспонируйте матрицу A1  
● Найдите обратную матрицу для А1  
● Создайте диагональную матрицу - поэлементно перемножив единичную
матрицу I и случайную матрицу A2 размерности 4 на 4  
● Создайте нулевую матрицу размерности 3 на 3  
● Для всех полученных матриц найдите: определитель, ранг и собственные
значения  
● Проанализируйте результаты

# Не понимаю на предмет чего я должен анализировать!!!

In [1]:
import numpy as np

● Создайте случайную матрицу А1 размерностью 5 на 5


In [69]:
8 + 0.5*np.random.randn(5, 5) # create array 5*5, where mean=8 and standard deviation=0,5

array([[7.74012941, 8.82376056, 8.22843744, 7.68612378, 7.44919763],
       [7.05651786, 7.0132393 , 7.24916887, 7.77834231, 8.59954116],
       [8.73853083, 8.3506896 , 8.20890993, 8.9393981 , 8.45023387],
       [7.49780828, 8.55942403, 7.42294359, 8.66355867, 7.49774137],
       [7.00795237, 8.80110842, 7.56637844, 7.22273296, 6.50148054]])

In [70]:
A1 = np.random.randint(10, size=(5,5)) # create array 5*5, where atribute "10" is max value of matrix's elements
A1

array([[5, 3, 3, 4, 7],
       [7, 9, 9, 7, 0],
       [2, 9, 1, 3, 3],
       [5, 0, 3, 5, 3],
       [8, 1, 9, 4, 2]])

● Транспонируйте матрицу A1


In [71]:
A1_Tr = A1.T.copy()
A1_Tr

array([[5, 7, 2, 5, 8],
       [3, 9, 9, 0, 1],
       [3, 9, 1, 3, 9],
       [4, 7, 3, 5, 4],
       [7, 0, 3, 3, 2]])

● Найдите обратную матрицу для А1

In [76]:
A1_inv = np.linalg.inv(A1)
A1_inv

array([[-0.76697531, -0.66100823,  0.8441358 ,  0.51028807,  0.65277778],
       [-0.09104938, -0.05298354,  0.1867284 , -0.02057613,  0.06944444],
       [ 0.50154321,  0.41615226, -0.55401235, -0.44032922, -0.26388889],
       [ 0.23919753,  0.33693416, -0.37191358,  0.08230453, -0.40277778],
       [ 0.37808642,  0.12397119, -0.23302469, -0.21399177, -0.15277778]])

In [77]:
A1@A1_inv # Сhecking correct invert A1

array([[ 1.00000000e+00,  0.00000000e+00,  4.44089210e-16,
        -4.44089210e-16, -4.44089210e-16],
       [-2.22044605e-16,  1.00000000e+00, -8.88178420e-16,
         2.22044605e-16, -4.44089210e-16],
       [-2.22044605e-16,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -3.33066907e-16],
       [-2.22044605e-16, -4.44089210e-16,  2.22044605e-16,
         1.00000000e+00, -3.33066907e-16],
       [ 2.22044605e-16,  1.38777878e-16, -2.77555756e-16,
         2.22044605e-16,  1.00000000e+00]])

● Создайте диагональную матрицу - поэлементно перемножив единичную
матрицу I и случайную матрицу A2 размерности 4 на 4


In [78]:
A2 = np.random.randint(10, size=(4,4)) # create array 5*5, where atribute "10" is max value of matrix's elements
A2

array([[9, 4, 8, 7],
       [9, 1, 6, 6],
       [9, 8, 9, 6],
       [5, 0, 1, 2]])

In [81]:
A2*np.eye(4)

array([[9., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 9., 0.],
       [0., 0., 0., 2.]])

● Создайте нулевую матрицу размерности 3 на 3

In [85]:
A3 = np.zeros([3,3])
A3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

● Для всех полученных матриц найдите: определитель, ранг и собственные
значения

In [91]:
np.linalg.det(A1) # Compute the determinant of the array

1943.9999999999984

In [87]:
np.linalg.det(A1_inv)

0.0005144032921810695

In [88]:
np.linalg.det(A1_Tr)

1944.0

In [89]:
np.linalg.det(A2*np.eye(4))

162.00000000000009

In [93]:
np.linalg.det(A3)

0.0

In [94]:
np.linalg.matrix_rank(A1) # Compute the matrix rank of the array

5

In [95]:
np.linalg.matrix_rank(A1_inv)

5

In [96]:
np.linalg.matrix_rank(A1_Tr)

5

In [97]:
np.linalg.matrix_rank(A2*np.eye(4))

4

In [98]:
np.linalg.matrix_rank(A3)

0

In [99]:
np.linalg.eigvals(A1) # Compute the eigenvalues of the array

array([22.26289266+0.j        , -8.29109932+0.j        ,
       -0.55034838+0.j        ,  4.28927752+0.85947771j,
        4.28927752-0.85947771j])

In [104]:
np.linalg.eigvals(A1_inv)

array([-1.81703089+0.j        , -0.12061127+0.j        ,
        0.22413996+0.04491276j,  0.22413996-0.04491276j,
        0.04491779+0.j        ])

In [105]:
np.linalg.eigvals(A1_Tr)

array([22.26289266+0.j        , -8.29109932+0.j        ,
       -0.55034838+0.j        ,  4.28927752+0.85947771j,
        4.28927752-0.85947771j])

In [106]:
np.linalg.eigvals(A2*np.eye(4))

array([9., 1., 9., 2.])

In [107]:
np.linalg.eigvals(A3)

array([0., 0., 0.])