# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
import numpy as np

In [4]:
A = np.random.randint(1, high=9, size=(3,3))
A

array([[3, 8, 8],
       [5, 6, 7],
       [8, 1, 8]])

In [10]:
A1 = np.eye(3)
A1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
A2 = A + A1
A2

array([[4., 8., 8.],
       [5., 7., 7.],
       [8., 1., 9.]])

In [20]:
A3 = A2 * np.array([1,2,3])
A3

array([[ 4., 16., 24.],
       [ 5., 14., 21.],
       [ 8.,  2., 27.]])

In [16]:
np.transpose(A2)

array([[4., 5., 8.],
       [8., 7., 1.],
       [8., 7., 9.]])

In [17]:
np.linalg.inv(A2)

array([[-5.83333333e-01,  6.66666667e-01, -2.77555756e-17],
       [-1.14583333e-01,  2.91666667e-01, -1.25000000e-01],
       [ 5.31250000e-01, -6.25000000e-01,  1.25000000e-01]])

In [22]:
## проверка на правильность вычисления обратной матрицы
np.linalg.inv(A2) @ A2

array([[ 1.00000000e+00, -6.93889390e-16, -9.15933995e-16],
       [ 2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
       [ 2.22044605e-16,  1.38777878e-16,  1.00000000e+00]])

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [24]:
m = np.array([[2,2],[1,3]])
m

array([[2, 2],
       [1, 3]])

In [31]:
print('собственные значения')
np.linalg.eig(m)[0]

собственные значения


array([1., 4.])

In [32]:
print('собственные векторы')
np.linalg.eig(m)[1]

собственные векторы


array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [81]:
for i in range(100000):
    A = np.random.randint(1, high=5, size=(3,3))
    det_A = np.linalg.det(A)
    if det_A == 1.0:
        print(A) 
        break


[[2 4 3]
 [1 3 3]
 [2 3 2]]
